import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'
import styles from '../styles/Home.module.scss'

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Brandeck</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Brandeck
        </h1>

        <div>Winding Road Games card preview/generation utility.</div>

        <div className={styles.grid}>
          <div className={styles.card}>
            <h2><Link href="/astromon/cards/3.0">Last Patch &rarr;</Link></h2>
            <p>View the last patch.</p>
          </div>

          <div className={styles.card}>
            <h2><Link href="/astromon/cards/3.0">In Progress Patch &rarr;</Link></h2>
            <p>View the in progress patch.</p>
          </div>

          <div
            className={styles.card}
          >
            <h2>Other Versions</h2>
            <p>Go to /game/cards/X.Y to view those cards.</p>
          </div>

          <div
            className={styles.card}
          >
            <h2>Generate (Admin) &rarr;</h2>
            <p>
              Generate images for each card and upload to Drive
            </p>
          </div>
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
        <p>2022 Winding Road Games</p>
      </footer>
    </div>
  )
}

export default Home
